### ISSUE TITLE
ZeroDivisionError 

### ISSUE THREAD

**Issue by AndoKarim** [xdevguild/multiversX-nft-holders#1]
Hello everyone,
tried to launch the script for my collection and it failed. 
Here are all the info : 
`Traceback (most recent call last):
  File "E:\Users\Karim\Desktop\nft\elrond-nft-holders\get-nfts-list.py", line 105, in <module>
    average = round(total_nft / len(values), 2)
ZeroDivisionError: division by zero
`

Ticker :  EMINERS-5b421

Thanks for your help

**Comment by PABourdais** [comment]
Hey @AndoKarim sorry for answering late, the good ticker for your collection is `EMINERS-5b421f` 

I am going to correct the 0 case right now

**Comment by PABourdais** [comment]
Fix: https://github.com/xdevguild/elrond-nft-holders/pull/2
